Filters are not applied to pagination
joemasilotti/railsdevs.com pull request #272
Opened 2022-02-03 16:51 UTC by kaushikhande

Fixes Issue: Filters are not applied to pagination #269 

Added filter params along with developer URL, so that filters are considered
for next page request.

### Pull request checklist

- [x] Your code contains tests relevant for code you modified
- [x] You have linted and tested the project with `bin/check`

2022-02-03 18:35 UTC, joemasilotti requested changes
Thanks for the PR! Along with my comment, can you also add a test that ensures the "next" page links render correctly?

2022-02-03 18:35 UTC, joemasilotti commented on app/queries/developer_query.rb
> +      role_types: @role_types || []
Why are we not using the `#sort`, `#time_zone`, and `#role_type` methods?

2022-02-04 05:09 UTC, kaushikhande commented
> Thanks for the PR! Along with my comment, can you also add a test that ensures the "next" page links render correctly?

Okay

2022-02-10 03:46 UTC, joemasilotti commented
@kaushikhande, thanks again for this PR. I had a business call out that pagination is broken when filtering. So I wanted to get this out ASAP and pushed a few commits.

2022-02-10 03:49 UTC, merged

2022-02-10 05:05 UTC, kaushikhande commented
@joemasilotti Thank you for merging my PR. I can totally understand your urgency. I was on vacation for last 2 days. I look into it last night but was having some difficulty in completing the pagination tests. Thank you once again.