Bugfix: Show "Edit my profile" if the user has already a dev profile
joemasilotti/railsdevs.com pull request #277
Opened 2022-02-06 07:17 UTC by salochara

Fixes #229 
-> In the developers index, show "Edit my profile" in the CTA button if the user has already a developer profile

### Pull request checklist

- [X] Your code contains tests relevant for code you modified
- [X] You have linted and tested the project with `bin/check`

2022-02-07 18:40 UTC, joemasilotti requested changes
Thanks for the PR! I'd love everything moved to a view component, including the tests.

2022-02-07 18:40 UTC, joemasilotti commented on test/integration/developers_test.rb
> +
These can be moved to the view component test.

2022-02-24 13:52 UTC, joemasilotti commented
Hey @salochara, do you still have appetite to make my requested changes? If not, no worries, I can take over. Just let me know.

2022-02-25 21:11 UTC, salochara commented
Hey @joemasilotti 👋 

Sorry. I haven't been able to get to this. 
Yeah.. it'd be better if you can take it over. 

I'll definitely try to keep on contributing once things stabilize on my side!

2022-02-26 03:39 UTC, dhairyagabha commented
@joemasilotti Can I work on this? I can have this done this weekend.

2022-02-26 14:26 UTC, joemasilotti commented
Go for it! Thanks for the heads up. 

I think all that's left is extracting the logic to a view component and changing the icon to a pencil for Edit.

2022-02-26 18:09 UTC, dhairyagabha commented
@joemasilotti added #301 fixing everything in #229 

It was easier to just create a new clean branch.

2022-02-27 00:24 UTC, closed without merging