Filter developers by role level
joemasilotti/railsdevs.com pull request #306
Opened 2022-02-28 06:27 UTC by themudassarhassan

This PR adds the functionality to filter by `Role Level` and closes [this](https://github.com/joemasilotti/railsdevs.com/issues/294) issue.
### Pull request checklist

- [x] Your code contains tests relevant for code you modified
- [x] You have linted and tested the project with `bin/check`

2022-03-01 18:21 UTC, joemasilotti requested changes
This looks great! Three things:

1. Remove the fixed width (there's a review comment suggestion)
2. PR #304 was just merged which adds mobile filtering - can you apply your changes to mobile, too?
3. I'm going to hide this behind a feature flag for now - role level is still new and only a few folks have added it

2022-03-01 18:21 UTC, joemasilotti commented on app/components/developer_query_component.html.erb
> +            <div data-toggle-target="element" class="origin-top-right absolute right-0 w-64 mt-2 bg-white rounded-md shadow-2xl p-4 ring-1 ring-black ring-opacity-5 focus:outline-none hidden">
```suggestion
            <div data-toggle-target="element" class="origin-top-right absolute right-0 mt-2 bg-white rounded-md shadow-2xl p-4 ring-1 ring-black ring-opacity-5 focus:outline-none hidden">
```

2022-03-02 06:00 UTC, themudassarhassan commented
I can tackle 1 and 2 myself, regarding point 3 I would need some information/guidance like do we have feature flag implemented now? and any code example would be helpful! Thanks

2022-03-02 16:41 UTC, joemasilotti commented
For 3, I've been doing something similar to the following:

```ruby
# app/models/feature.rb

class Feature
  def self.enabled?(feature_name)
    case feature_name.to_sym
    when :role_level_filters
      !Rails.env.production?
    end
  end
end
```

```ruby
# some view

<% if Feature.enabled?(:role_level_filters) do %>
  <%= form.checkbox :role_level_junior %>
<% end %>
```

2022-03-02 16:41 UTC, joemasilotti commented
`main` will also need to be merged in before you work on the mobile filtering.

2022-03-03 06:55 UTC, themudassarhassan commented
Okay thanks! I'll look into it.

2022-03-06 02:59 UTC, themudassarhassan commented
Hey @joemasilotti I have pushed the changes. Please have a look when you get some time. Thanks!

2022-03-06 21:08 UTC, joemasilotti commented on app/models/feature.rb
> +      true
```suggestion
      Rails.env.development?
```

2022-03-06 21:09 UTC, joemasilotti reviewed
Outside of the one request can you merge in `main`? Then we can merge this in!

2022-03-07 07:11 UTC, themudassarhassan commented
Hey @joemasilotti I have merged main in and also this filtering feature was need to be enabled for `test` env for the tests to be passed. I have made that change as well.

2022-03-07 17:14 UTC, joemasilotti commented
Looks great - thank you for the contribution!

2022-03-07 17:14 UTC, merged