Resize avatars to displayed sizes
joemasilotti/railsdevs.com pull request #518
Opened 2022-06-23 01:30 UTC by bradpurchase

Closes #513.

- Uses ActiveStorage variants to resize avatars to their displayed sizes and updates the `AvatarComponent` component to make it easy to optionally display avatars as a variant.
- Adds `image_processing` to the Gemfile as this is required by ActiveStorage for resizing
- Adds `vips` to the Brewfile as this is a dependency of `image_processing` 

## Pull request checklist

- [x] My code contains tests covering the code I modified
- [x] I linted and tested the project with `bin/check`
- [x] I added significant changes and product updates to the [changelog](CHANGELOG.md)

2022-06-23 12:31 UTC, joemasilotti commented
This is looking good!

A few questions:

1. Do we need all the changes to the Brewfile.lock? It looks like a bunch of packages got updated. I'd prefer to not do that in this PR if possible. And stick to only adding the vips-related stuff. 
2. Does this handle 2x screen resolutions? I don't see that anywhere. 
3. Do we need a backfill to resize all the existing images? Or will the first few page loads take a performance hit?

2022-06-23 13:14 UTC, bradpurchase commented
Quick note on the first point: interestingly enough, it seems like using `brew bundle install --no-upgrade` will in fact still upgrade if homebrew determines it "needs to". See [this thread](https://github.com/Homebrew/homebrew-bundle/issues/632) 😕

2022-06-23 14:14 UTC, joemasilotti commented
Awesome, thanks!

So we will serve 2x to everyone? If so, can you log an issue to add 1x and 2x via HTML to browsers?

And yes, let's create a script that will generate all variants of avatars that don't exist. Then I can backfill it before running the audit again.

2022-06-23 15:20 UTC, bradpurchase commented
> So we will serve 2x to everyone? If so, can you log an issue to add 1x and 2x via HTML to browsers?

Yes. Do you mean specifying e.g. `@2x` on the image src in HTML? I can create an issue for that, if so.

> And yes, let's create a script that will generate all variants of avatars that don't exist. Then I can backfill it before running the audit again.

Sure, I'll get on that!

2022-06-23 15:28 UTC, joemasilotti commented
Yes please! And sounds great, thanks.

2022-06-23 22:37 UTC, bradpurchase commented
I've provided the backfill task, and created the issue [here](https://github.com/joemasilotti/railsdevs.com/issues/519). Let me know if there's anything I should add to that issue, or any other way I can help!

2022-06-24 01:08 UTC, joemasilotti commented
Is it possible to only process variants for those that don't exist?

2022-06-24 02:15 UTC, bradpurchase commented
> Is it possible to only process variants for those that don't exist?

Actually I believe `.processed` takes care of that, it will either process the variant if it doesn't exist, or return the processed variant if it does. See [here](https://edgeapi.rubyonrails.org/classes/ActiveStorage/Variant.html#method-i-processed).

2022-06-24 03:06 UTC, joemasilotti commented
Beautiful!

I'm going to dig through the code one more time and do some local testing this weekend.

2022-06-24 03:13 UTC, joemasilotti requested changes
To sanity check, the avatars on the homepage and /developers are the same size as when viewing a developer profile. Right?

I made a few suggestions and questions in-line. But other than that this looks good to me!

I still need to do some manual testing.

2022-06-24 03:13 UTC, joemasilotti commented on .github/workflows/ci.yml
> +      - name: Install system deps
```suggestion
      - name: Install system dependencies
```

2022-06-24 03:13 UTC, joemasilotti commented on .github/workflows/ci.yml
> +          sudo apt-get install -yqq libvips-dev
Is there no built in or third party Action to get us this? If not, is this the recommended way for CI? Genuine question.

2022-06-24 03:13 UTC, joemasilotti commented on app/components/avatar_component.rb
> +    @image = image
I'm not sure what this line is doing.

2022-06-24 03:13 UTC, joemasilotti commented on test/components/avatar_component_test.rb
> +    assert_equal true, avatar_component.image.is_a?(ActiveStorage::VariantWithRecord)
```suggestion
    assert_instance_of ActiveStorage::VariantWithRecord, avatar_component.image
```

2022-06-24 12:11 UTC, merged

2022-06-25 12:01 UTC, joemasilotti commented
## PageSpeed score for `/developers`

### Mobile

* Before: 76, 79, 79
* After: 77, 82, 82

2022-06-27 14:30 UTC, joemasilotti commented
The following changes were required to get vips working on Heroku:

1. Add the [apt buildpack](https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku-community/apt.tgz) at index 0
2. Add the [heroku-buildpack-vips buildpack](https://github.com/brandoncc/heroku-buildpack-vips) as the last buildpack
3. Add the following to `Aptfile`:

```
libglib2.0-0
libglib2.0-dev
libpoppler-glib8
```