Toggle 'Sort' button's aria-expanded attribute value.
joemasilotti/railsdevs.com pull request #580
Opened 2022-07-17 17:52 UTC by axhgl

This should address issue #539.

Small background regarding the thinking for this implementation:

We add a Stimulus.js `AccessibilityController` where we define actions that handle the updating of values of accessibility related attributes, e.g. in this case it is `#toggleAriaExpanded` to handle "aria-expanded", while in the future it might be a case where we add `#toggleAriaChecked` for handling the "aria-checked" attribute.

I briefly wondered: should there be an integration test covering this?

## Pull request checklist

- [ ] My code contains tests covering the code I modified
- [x] I linted and tested the project with `bin/check`
- [ ] I added significant changes and product updates to the [changelog](CHANGELOG.md)

2022-07-20 15:47 UTC, joemasilotti requested changes
Looks good to me. I made two minor suggestions – once those are taken care of I can merge this in. Thanks for the contribution!

2022-07-20 15:47 UTC, joemasilotti commented on app/javascript/controllers/index.js
> +application.register("accessibility", AccessibilityController)
Can you run `bin/rails stimulus:manifest:update` so this gets sorted correctly?

2022-07-20 15:47 UTC, joemasilotti commented on app/javascript/controllers/accessibility_controller.js
> +    const el = this.buttonTarget;
```suggestion
    const element = this.buttonTarget;
```

2022-07-21 17:45 UTC, axhgl commented
It should be alright now. By the way, I squashed the couple small fixing commits.

2022-07-21 18:26 UTC, joemasilotti commented
Looks great! Thanks for the update.

2022-07-21 18:26 UTC, merged