removed twitter method #603
joemasilotti/railsdevs.com pull request #607
Opened 2022-08-19 05:42 UTC by sarthakw7

## Pull request checklist

- [ ] My code contains tests covering the code I modified
- [ ] I linted and tested the project with `bin/check`
- [x] I added significant changes and product updates to the [changelog](CHANGELOG.md)

2022-08-19 12:54 UTC, joemasilotti requested changes
Looks great! I made two small requests then we are good to merge.

2022-08-19 12:54 UTC, joemasilotti commented on app/components/developers/open_graph_tags_component.rb
Please remove this blank line.

2022-08-19 12:54 UTC, joemasilotti commented on CHANGELOG.md
> +* August 19 - Removed Twitter method from developer Open Graph tags #603
```suggestion
* August 19 - Removed developer Twitter handle from Open Graph tags #607
```

2022-08-19 14:03 UTC, sarthakw7 commented
Sure .

2022-08-19 15:06 UTC, joemasilotti commented
Thanks! It looks like there are some test failures though.

I think you can remove line 23 in `test/components/developers/open_graph_meta_tags_component_test.rb` and the entire test on line 35.

2022-08-20 04:14 UTC, joemasilotti approved these changes
Looks great – thanks for the contribution!

2022-08-20 04:20 UTC, merged

2022-08-20 04:21 UTC, sarthakw7 commented
Glad to help!