Check for deleted developers in conversation
joemasilotti/railsdevs.com pull request #751
Opened 2023-01-17 02:34 UTC by troyizzle

I haven't wrote some test but wanted to make sure this is what you were looking to implement.
Let me know what you think @joemasilotti 
![4DJyP2l](https://user-images.githubusercontent.com/43835286/212797162-3531c3d8-4b8e-4a0c-a926-31136c65036e.png)
![e3XEBtA](https://user-images.githubusercontent.com/43835286/212797166-0ecede48-8fca-417e-854c-b025e5f2014f.png)

## Pull request checklist

- [ ] My code contains tests covering the code I modified
- [ ] I linted and tested the project with `bin/check`
- [ ] I added significant changes and product updates to the [changelog](CHANGELOG.md)

Closes #747

2023-01-17 14:52 UTC, joemasilotti commented
Pretty much, yeah! Let's change the copy to `(deleted account)`.

I am also pretty sure the messages and conversations will cascade delete. (Can you double check that for me?)

If that's correct then you won't be able to click into a conversation, so the link will need to be removed in a list.

2023-01-18 00:07 UTC, troyizzle commented
I don't believe the messages get deleted, just the notifications.


Let me know what you think!

2023-01-24 18:21 UTC, joemasilotti commented
You are correct! Messages/conversations are _not_ deleted when the `User` is deleted.

Please proceed with implementing the change request above and adding some tests. Thank you!

2023-01-25 02:55 UTC, troyizzle commented
> You are correct! Messages/conversations are _not_ deleted when the `User` is deleted.
> 
> Please proceed with implementing the change request above and adding some tests. Thank you!

I think this should be ready now!

2023-01-26 17:23 UTC, joemasilotti requested changes

2023-01-26 17:23 UTC, joemasilotti commented on app/models/conversation.rb
> +    developer.nil? | business.nil?
```suggestion
    developer.nil? || business.nil?
```

...right?

2023-01-26 17:28 UTC, joemasilotti commented
If I'm a business and view a conversation with a deleted developer it still says "Conversation with #{business}" in the <h1> and <title>.

2023-01-26 17:56 UTC, troyizzle commented
Thanks Joe!
Should the `deleted_account` i18n key be moved into something more common, like at the root, its being used a couple different times.

Hope this fixes that title problem
![image](https://user-images.githubusercontent.com/43835286/214912057-078faa68-19e3-48af-b8a0-96d1dce93193.png)

2023-01-26 18:04 UTC, joemasilotti commented
That would be great! My rule is if it’s used in 3 or more places to extract it to a common area.

2023-01-26 21:26 UTC, joemasilotti requested changes
Almost there! The `<title>` tag on a conversation still needs to be updated.

2023-01-26 22:43 UTC, joemasilotti commented
Awesome, thank you! Going to merge in now.

There might be a refactor down the line with the repeated check... if you have appetite feel free to give it a pass. But this looks good for now.

2023-01-26 22:53 UTC, merged