New hire form flow
joemasilotti/railsdevs.com pull request #775
Opened 2023-02-07 22:41 UTC by RomanTurner

Flow for businesses to notify RailsDevs when they make a hire
[issue 764](https://github.com/joemasilotti/railsdevs.com/issues/764) 

## Pull request checklist

- [x] My code contains tests covering the code I modified
- [x] I linted and tested the project with `bin/check`
- [x] I added significant changes and product updates to the [changelog](CHANGELOG.md)

2023-02-07 22:46 UTC, RomanTurner commented
I would have like to put the following tests around the nav_bar states:
- [ ] As a business with a developer profile: do both "Found a job?" and "Made a hire?" on the navigation bar show? 
- [ ] As an admin: Does the Admin dropdown navigation menu have the "Hire forms" link?

I don't have a lot of experience with testing, any pointers?

2023-02-07 23:06 UTC, RomanTurner commented
Getting this message: 

```bash
✓ Perfect! No inconsistent interpolations found.
✓ Good job! All data is normalized
```
Not sure why it is failing.

2023-02-08 00:00 UTC, joemasilotti commented
The best spot for these tests is probably in the navigation bar view component. Play with that for a bit. If you can't figure it out let's pair!

2023-02-26 20:58 UTC, joemasilotti commented
Hey @RomanTurner, three week check in. Do you still have appetite to finish this PR?

If not, no worries. I can take it over the finish line.

2023-02-27 01:50 UTC, RomanTurner commented
> Hey @RomanTurner, three week check in. Do you still have appetite to finish this PR?
> 
> 
> 
> If not, no worries. I can take it over the finish line.


Definitely, I am just coming back from vacation and can finish the tests up for this. The feature is complete upto that point

2023-02-27 02:28 UTC, joemasilotti commented
Excellent! Looking forward to it.

2023-03-03 15:08 UTC, RomanTurner commented
@joemasilotti It keeps failing on the i18n-tasks but the console output is: 

```
✓ Perfect! No inconsistent interpolations found.
✓ Good job! All data is normalized
```

2023-03-03 15:24 UTC, joemasilotti commented
I think that's the output from normalizing. Can you try running the health check, too?

`bundle exec i18n-tasks health en`

2023-03-03 16:52 UTC, joemasilotti requested changes
This is looking great, nice work Roman!

Outside of the tiny nitpicking code requests, I have to changes:

1. Let's change the two admin buttons to "Developer forms" and "Business forms" because right now "Hire" vs. "Hired" is a little confusing.
2. Let's add a a mailer preview for the new admin email.

2023-03-03 16:52 UTC, joemasilotti commented on CHANGELOG.md
> +* March 3 - Added business new hire forms and admin new hire forms
Please add the PR # and your handle like the other entries.

2023-03-03 16:52 UTC, joemasilotti commented on app/components/nav_bar/user_component.html.erb
> -
Please add back in these removed lines.

2023-03-03 16:52 UTC, joemasilotti commented on app/controllers/hire/forms_controller.rb
> +      ).merge(business: current_user.business)
```suggestion
      ).merge(business: business)
```

2023-03-03 16:52 UTC, joemasilotti commented on app/models/hire/form.rb
> +    self.table_name = "hire_forms"
```suggestion
    self.table_name = "hire_forms"
    include Hire::Notifications
```

Code preference :)

2023-03-03 16:52 UTC, joemasilotti commented on config/locales/en.yml
> +        title: "%{business} has hired a developer"
```suggestion
        title: "%{business} hired a developer"
```

2023-03-03 16:52 UTC, joemasilotti commented on db/schema.rb
> +
Let's remove all the changes that aren't for the new table and index.

2023-03-03 16:52 UTC, joemasilotti commented on test/components/nav_bar/user_component_test.rb
> +    assert_link_to about_path
What's the point of these tests?

2023-03-03 16:52 UTC, joemasilotti commented on app/views/admin/hire/forms/show.html.erb
> +        <%= render Admin::BasicLinkComponent.new(@form.business.name, business_path(@form.business)) %>
Let's also add their email address in this same column that links with a `mailto:`.

2023-03-17 22:42 UTC, MikeRayUX commented
Hey guys! Happy to push this one forward!

2023-03-17 22:44 UTC, joemasilotti commented
All yours @MikeRayUX - thanks for reaching out on Twitter!

@RomanTurner, thanks for getting most of the work done. I'm planning on awarding both of you the full bounty.

2023-03-20 18:00 UTC, closed without merging

2023-03-20 20:58 UTC, MikeRayUX commented
No problem @RomanTurner, thank you for your work on this!