fix: Preview image doesn't change when select new avatar in profile page
joemasilotti/railsdevs.com pull request #787
Opened 2023-02-26 23:25 UTC by ryy

closes #781

Preview image doesn't change when select new avatar in profile page

## Pull request checklist
- [ ] My code contains tests covering the code I modified
  - sorry, I couldn't work system spec.
- [ ] I linted and tested the project with `bin/check`
  - All passed except system spec
- [ ] I added significant changes and product updates to the [changelog](CHANGELOG.md)

## Evidence
https://user-images.githubusercontent.com/13917558/221443418-83bd612a-d96b-497d-8068-d4d21e81acad.mov

2023-03-01 15:56 UTC, joemasilotti requested changes

2023-03-01 15:56 UTC, joemasilotti commented on app/javascript/controllers/file_upload_controller.js
> +    }
Can we convert this to another Stimulus target? Iterating over `this.pictureTargets` feels a lot cleaner.

2023-03-15 14:06 UTC, joemasilotti commented
Hey again @ryy, do you still have appetite to finish this PR? If not, no worries! Let me know and I can take it over the finish line if need be.

2023-03-15 15:50 UTC, joemasilotti approved these changes

2023-03-15 15:51 UTC, joemasilotti commented
Thanks for your contribution @ryy!

2023-03-15 15:55 UTC, merged

2023-03-16 13:42 UTC, ryy commented
@joemasilotti 
Sorry, I was a little busy.
Thank you for help me.