Reworked Stale Developers Logic
joemasilotti/railsdevs.com pull request #847
Opened 2023-03-29 20:14 UTC by anoosh96

this will address #840

- [x ] My code contains tests covering the code I modified
- [ x] I linted and tested the project with `bin/check`
- [ ] I added significant changes and product updates to the [changelog](CHANGELOG.md)

2023-03-31 22:12 UTC, joemasilotti reviewed
Do we need to keep track of if a developer was notified anymore?

With the new logic, we will be marking stale profiles as not interested. If someone isn't interested I don't care if their profile hasn't been updated in a month - and I don't think we need to notify them about it.

I think the new logic can check if the developer is actively (looking or open to offers) _and_ hasn't been updated in more than 1 month. If so, mark them as not interested and send the email.

The next time the query is run they won't be included because they are no longer actively looking or open to offers.

Does that make sense? If so, would you like to apply the necessary changes?

**Edit**: We can use `Developer.actively_looking_or_open` to include `nil`, too. And lets change the threshold from one month to three.

2023-04-01 13:05 UTC, anoosh96 commented
> Do we need to keep track of if a developer was notified anymore?
> 
> With the new logic, we will be marking stale profiles as not interested. If someone isn't interested I don't care if their profile hasn't been updated in a month - and I don't think we need to notify them about it.
> 
> I think the new logic can check if the developer is actively (looking or open to offers) _and_ hasn't been updated in more than 1 month. If so, mark them as not interested and send the email.
> 
> The next time the query is run they won't be included because they are no longer actively looking or open to offers.
> 
> Does that make sense? If so, would you like to apply the necessary changes?
> 
> **Edit**: We can use `Developer.actively_looking_or_open` to include `nil`, too. And lets change the threshold from one month to three.

@joemasilotti  that depends more on the requirements if we want to keep reminding the developer that their profile has been inactivated or just notify them once. I was thinking about, what if the developer misses the email?. If we don't want to keep notifying them then it totally makes sense. I will make these changes

2023-04-01 15:46 UTC, joemasilotti commented
I’m fine with only notifying them once. If they miss the email, that’s in them in my opinion. 

And because we are sending it via a notification we will always have a record that we sent it. So we can update logic accordingly in the future.

2023-04-01 21:42 UTC, anoosh96 commented
> I’m fine with only notifying them once. If they miss the email, that’s in them in my opinion.
> 
> And because we are sending it via a notification we will always have a record that we sent it. So we can update logic accordingly in the future.

that makes sense, thanks for the clarification.

2023-04-03 11:07 UTC, anoosh96 commented
Hey @joemasilotti, I have made the requested changes.

2023-04-04 18:21 UTC, joemasilotti requested changes
This is looking good! I made a few requests and pushed some copy updates.

2023-04-04 21:25 UTC, anoosh96 commented on app/models/concerns/developers/notifications.rb
> +      send_stale_profile_notification if mark_stale
I think update_column can return false as well if something goes wrong with updating the column (there's a possibility), ref:
[](https://apidock.com/rails/ActiveRecord/Persistence/update_columns)

2023-04-04 21:33 UTC, anoosh96 commented on app/queries/stale_developers_query.rb
> +  def stale_developers
yes, I better move this into Custodian, as its only being used in one place.

2023-04-04 21:36 UTC, anoosh96 commented on app/models/developers/custodian.rb
> +      stale_developers.profile_reminder_notifications
it returns the developers that were marked stale and notified, and we are logging that number in the rake task, we can move the logging to Custodian class if required.

2023-04-05 12:30 UTC, anoosh96 commented
> This is looking good! I made a few requests and pushed some copy updates.

Hey @joemasilotti Thanks for the commits, I really missed out on those little things, also I have pushed some changes regarding the comments, looking forward to your feedback.

2023-04-05 12:39 UTC, joemasilotti commented on app/models/concerns/developers/notifications.rb
> +      send_stale_profile_notification if mark_stale
Got it, thanks!

2023-04-05 12:39 UTC, joemasilotti commented on app/models/developers/custodian.rb
> +      stale_developers.profile_reminder_notifications
Ah, right. Thanks for clarifying.

2023-04-05 12:41 UTC, joemasilotti approved these changes
This looks great, thanks @anoosh96!

I'm going to wrap it in a feature flag as I work on one other coordinated issue. But please [email me](mailto:joe@masilotti.com) how you'd like to receive your bounty (Venmo, PayPal, Zelle, or Wise).

2023-04-05 13:15 UTC, anoosh96 commented
Hey @joemasilotti, I am actually located in Pakistan, so these won't work for me, can I send you my IBAN, I mostly recieve international payments through my IBAN.

2023-04-05 13:29 UTC, joemasilotti commented
I'm not sure what IBAN is but I bet we can figure something out! Email me so we don't end up sending back information in public. :)

2023-06-05 12:59 UTC, closed without merging